import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/authContext";
import { TaskProvider } from "./context/taskContext";
import Navbar from "./components/Navbar";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <TaskProvider> 
            <main className="w-[80%] max-w-[1280px] mx-auto">
            {children}
            </main>                    
          </TaskProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
