import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/authContext";
import { TaskProvider } from "./context/taskContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Alien duce </h1>
        <AuthProvider>
          <TaskProvider>
            <h1>Hola mundo</h1>
            {children}
          </TaskProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
